easy_admin:
    site_name: Widget-bygger

    design:
        brand_color: '#b81b40'

        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@ItkDevConfig/easy_admin/form/setting.html.twig'

        menu:
            - entity: 'Widget'
              label: Widgets
            - entity: 'WidgetContext'
              label: Widget contexts
            - entity: 'User'
              icon: 'user'
              label: Users
            - entity: 'Setting'
              icon: 'cog'
              label: Settings
            - label: 'Widget builder'
              route: 'default'

    entities:
        Widget:
            templates:
                list: 'admin/list/widget.html.twig'

            class: App\Entity\Widget
            disabled_actions: ['new', 'delete', 'edit']
            list:
                role: ROLE_ADMIN
                actions:
                    - name: show
                      label: Show
                    - name: widget_edit
                      type: route
                      label: Edit
                    - name: admin_loggable_entity
                      type: route
                      label: Revisions

                fields:
                    - property: title
                    - property: context
                    - property: createdBy
                    - property: createdAt
            form:
                role: ROLE_ADMIN
                fields:
                    - property: title

            show:
                role: ROLE_ADMIN
                fields:
                    - property: title
                    - property: statistics
                      template: easy_admin/statistics.html.twig

        WidgetContext:
            label: Context
            class: App\Entity\WidgetContext
            disabled_actions: ['delete']
            list:
                role: ROLE_ADMIN
                fields:
                    - property: name
                    - property: host

            form:
                role: ROLE_ADMIN
                fields:
                    - property: name
                    - property: host
                    - property: configuration
                      type: App\Form\Type\YamlType
                      help: |
                          Example:
                          <pre>
                          name: 'ereolen'
                          host: 'widget.ereolen.dk'
                          label: 'eReolen'
                          url: 'https://www.ereolen.dk'
                          search_link: '<a href="https://ereolen.dk/search/ting" target="_blank">eReolen</a>'
                          logo: '/images/eReolen_Logo.svg'
                          search_url: 'https://www.ereolen.dk/search/ting'
                          ereol_widget_search_url: 'https://itk:itk@stg.ereolen.dk/widget/search'
                          </pre>

        User:
            class: App\Entity\User
            role_prefix: ROLE_ADMIN_USER
            disabled_actions: ['delete']
            list:
                fields:
                    - property: email
                    - property: enabled
                      type: boolean
                    - property: roles
                    - property: createdBy
                    - property: createdAt
                    - property: lastLogin
            form:
                fields:
                    - property: email
                    - property: enabled
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN

            new:
                fields:
                    - property: email
                    - property: enabled
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices:
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN

        Setting:
            controller: ItkDev\ConfigBundle\Controller\SettingController
            class: ItkDev\ConfigBundle\Entity\Setting
            disabled_actions: [new, delete]
            list:
                fields:
                    # - property: section
                    - property: name
                    - property: description
                    # - property: type
                    # - property: formType
                    - property: value
                      label: Value
                      template: '@ItkDevConfig/easy_admin/Setting/display_value.html.twig'

            edit:
                fields:
                    - property: name
                      # Important: "name" must be disabled to not overwrite the name when saving a setting
                      type_options:
                          disabled: true
                    - property: value
                      # type_options:
                      #     Optionally, make "value" non-required
                      #     required: false
                      #     Optionally, hide the "Value" label
                      #     label: false
                    - property: description
                      # Important: "description" must be disabled to not overwrite the name when saving a setting
                      type_options:
                          disabled: true
